
values = {
    "meioa": "{MAIN}",
    "allr": "{INT}",
    "fljota": "{FLOAT}",
    "aundan": "{BOOL}",
    "ef": "{IF}",
    "ella": "{ELSE}",
    "stund": "{WHILE}",
    "saor": "{TRUE}",
    "flar": "{FALSE}",
    "rita": "{PRINT}",
    "lesa": "{SCAN}",
    "=": "{=}",
    "+": "{+}",
    "-": "{-}",
    "*": "{*}",
    "/": "{/}",
    "!": "{NOT}",
    "&": "{AND}",
    "|": "{OR}",
    "==": "{EQUAL}",
    "<": "{LESS}",
    ">": "{MORE}",
    "!=": "{DIFF}",
    ";": "{;}",
    "{": "{{}",
    "}": "{}}",
    "(": "{(}",
    ")": "{)}",
}
